server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: register-service
          uri: lb://register-service
          predicates:
            - Path=/api/client/**
        - id: credit-application-service
          uri: lb://credit-application-service
          predicates:
            - Path=/api/application/**
        - id: credit-evaluation-service
          uri: lb://credit-evaluation-service
          predicates:
            - Path=/api/creditEvaluation/**
        - id: credit-follow-up-service
          uri: lb://creditFollowUp-service
          predicates:
            - Path=/api/credit-follow-up/**
        - id: loan-type-service
          uri: lb://loan-type-service
          predicates:
            - Path=/api/loanType/**