apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-application-deployment
  labels:
    app: credit-application-deployment
spec:
  selector:
    matchLabels:
      app: credit-application-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: credit-application-deployment
    spec:
      containers:
        - name: credit-application
          image: quasaride/prestabanco-credit-application
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_CREDIT_APPLICATION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_CREDIT_APPLICATION
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_CREDIT_APPLICATION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_CREDIT_APPLICATION
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_CREDIT_APPLICATION
---
apiVersion: v1
kind: Service
metadata:
  name: credit-application-service
  labels:
    app: credit-application-service
spec:
  selector:
    app: credit-application-deployment
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
  type: NodePort