apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-type-deployment
  labels:
    app: loan-type-deployment
spec:
  selector:
    matchLabels:
      app: loan-type-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: loan-type-deployment
    spec:
      containers:
        - name: loan-type
          image: quasaride/prestabanco-loan-type
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_LOAN_TYPE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_LOAN_TYPE
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_LOAN_TYPE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_LOAN_TYPE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_LOAN_TYPE