apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-deployment
  labels:
    app: register-deployment
spec:
  selector:
    matchLabels:
      app: register-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: register-deployment
    spec:
      containers:
        - name: register
          image: quasaride/prestabanco-register
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REGISTER
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REGISTER
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_REGISTER
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REGISTER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REGISTER
---
apiVersion: v1
kind: Service
metadata:
  name: register-service
  labels:
    app: register-service
spec:
  selector:
    app: register-deployment
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 0
  type: NodePort